name: Build and publish docker-image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOCKER_REGISTRY: ghcr.io
  REGISTRY_IMAGE_NAME: ghcr.io/baboon-co/iron-forge/api-gateway

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Log into docker registry ${{ env.DOCKER_REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0

      - name: Bump version
        id: versioning
        uses: nsmolianitski/semver-action@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build -t $REGISTRY_IMAGE_NAME:${{ steps.versioning.outputs.new_version }} .

      - name: Tag as 'latest'
        run: docker tag $REGISTRY_IMAGE_NAME:${{ steps.versioning.outputs.new_version }} $REGISTRY_IMAGE_NAME:latest

      - name: Push image to registry
        run: |
          docker push $REGISTRY_IMAGE_NAME:${{ steps.versioning.outputs.new_version }}
          docker push $REGISTRY_IMAGE_NAME:latest